services:
  web:
    build: .
    container_name: wediga-dev
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./content:/app/content:ro
      - ./static:/app/static:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
